// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIN1rVjMgw6r80hYuTRrpSpsV8BH0WEn0',
    appId: '1:218660887469:web:f58ff04ccc90108522df24',
    messagingSenderId: '218660887469',
    projectId: 'nightride-a9173',
    authDomain: 'nightride-a9173.firebaseapp.com',
    storageBucket: 'nightride-a9173.firebasestorage.app',
    measurementId: 'G-4Y7N497G5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9psJRDieD_hhluJEDYKEey6efWn3X-8',
    appId: '1:218660887469:android:28c38d7a349bc81922df24',
    messagingSenderId: '218660887469',
    projectId: 'nightride-a9173',
    storageBucket: 'nightride-a9173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVJd4jHrz5TFxHTdLsrJ3c8GaFqtzY8w',
    appId: '1:218660887469:ios:b8f01140e713450822df24',
    messagingSenderId: '218660887469',
    projectId: 'nightride-a9173',
    storageBucket: 'nightride-a9173.firebasestorage.app',
    androidClientId: '218660887469-g2se66585c1elfsirdagr592gpfv4k2r.apps.googleusercontent.com',
    iosClientId: '218660887469-1jp1engmlb0bsa9d4rrnk9qshi0eb9f3.apps.googleusercontent.com',
    iosBundleId: 'com.therisetechvillage.nightride',
  );
}
